### PR TITLE
Multiline

### PR DESCRIPTION
**Pull request by Amndeep7**
Tried to change as little as possible API-wise so that it's just a minor version bump as opposed to a major version bump.  Basically instead of only being able to pass in an array for the data, you could also pass in an array holding all the arrays of data and also that wrapper array has a property assigned called "allkeys" which is an array that is a unique set of all the possible domain values.  Additionally, added on support for multiple line colors - basically pass in an array for the "lineColors" argument that I added - indices correspond between this array and the data wrapper array; if there are more data arrays than colors, default to "lineColor".  Let me know if you need any naming/formatting changes.  

Modified the readme to showcase the new data functionality, but didn't do it for the linecolors part since you guys didn't document any of the other parameters and I wasn't sure what you wanted to do for that.

Tangentially, what is the name for the pattern you're using in the arguments section of the function?  Never seen that thing before where you make variables inside of an object like that - took me a while to figure out what was happening since my google-fu apparently wasn't up to the task.

Example of what it looks like in use:
Example of what it looks like in use

### CODE REVIEW

**Comment by Amndeep7** [comment]
Would also satisfy the feature requests in #5 and #7.

**Comment by Amndeep7** [comment]
@bradoyler figured I should tag you so you'd see the pr

**Comment by bradoyler** [comment]
Well, @geekplux is the author here...

**Review by geekplux — COMMENTED** [review]
Thanks for this sweet PR, LGTM.

And it is better to update README more clearly, like update the preview pic and give a demo data under the preview. The requirement of data format is now a little abstract. What do you think? @Amndeep7

**Comment by Amndeep7** [comment]
Well the data format is better than it was haha - you have it as just `Data from file or web processed by d3 library.`, which doesn't specify how it's supposed to be an array of objects with keys of "key" and "value."  That took me a bit to figure out from reading the code.  I can add an example of what sample data should look like though.  I think that leaving the example pic that's already there is fine since it provides a clear and simple picture of the primary functionality; however, it'd be a good idea to add an example usage of the multiline capabilities - I can even use some of the other api options that aren't listed in the readme so that users get a clue to look at the code.

Please let me know if completing the below todo list will be good enough to merge the pr:

- Add an example of what the data structure should look like into the readme for both the single line and multiline variants
- Change name of folder from `example` to `examples`
- Add example usage of multiline functionality including creating the appropriate data structure, using options not listed in the readme such as linecolors, and outputting

**Comment by geekplux** [comment]
Awesome, it's good enough if your todo would have done, thanks again.
Any help you need me to do, plz tell me.

**Comment by Amndeep7** [comment]
@geekplux added the changes I mentioned in the todo - wanted to bring notice to the fact that I upgraded the version of d3node-output that this module uses, dunno if that's fine by you

**Comment by geekplux** [comment]
I've update the `allKeys` to `keys`, fix the error of multiline output and update the examples code for multiline.

**Comment by Amndeep7** [comment]
@geekplux 
You're gonna have to hotfix back the `allkeys`->`keys` cause `keys` is already there as a [function for arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/keys).  I actually ran into that issue when I was developing it cause I originally called it keys until I realized that it was causing my checks for it being a multiline variant to always go off because `keys` is always defined.  I'm open to changing the name of the variable if you want it to be something different from `allkeys`, but it cannot be `keys`.

**Comment by Amndeep7** [comment]
This is easy enough to confirm as well - if you try running the multiline example, it works fine, but if you try running the single line example, it does not generate the graph appropriately.

Below are the results from running the examples with your changes.  As you can see, the graph for the single line (bottom) is messed up.  
output-multiline
output

**Comment by geekplux** [comment]
emm...What you said is right, I'll fix it.

**Pull request merged**
